#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend Lamia1998
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 373042-web-01 54.175.189.216
        server 373042-web-02 54.89.118.190
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
